### ISSUE TITLE
Installed extension but invoking any command == not found

### ISSUE THREAD

**Issue by codepope** [joedevivo/vscode-circuitpython#1]
Installed the extension and no apparent errors in install but no command resolves:

e.g. calling update all libraries gives:

command 'circuitpython.circup.update' not found

**Comment by joedevivo** [comment]
Windows or Linux?

It looks like both are broken because the module I use for serialport communication has native components. I'll need to figure out how to build those for each platform before packaging. I've got some ideas but there are further complications on windows, but I should have something soon that handles those as well.

**Comment by codepope** [comment]
macOS. I'll pull the code down and see if I can't get a better handle on it.

**Comment by joedevivo** [comment]
Did you upgrade to the latest vscode? The last release did a major version upgrade of electron from 6 to 7 which might have broken some things. If you go to "About Visual Studio Code", it'll give you all the version info

**Comment by codepope** [comment]
Yup, it looks like serialport and a module version mismatch.

**Comment by NightSkySK** [comment]
Hi I've got the same problem on Windows. 
![image](https://user-images.githubusercontent.com/52137446/76557145-43e4d480-649b-11ea-9a8b-15c01fc4e38a.png)

On each command from Command Pallet --> Circuit Python: xxx I get 
command == not found
![image](https://user-images.githubusercontent.com/52137446/76557221-70005580-649b-11ea-9add-4eb2db368b6d.png)

**Comment by joedevivo** [comment]
I didn't mean to close this, but 0.0.2 is in and it should work now. Take it for a spin on mac, windows or linux :D

**Comment by avondohren** [comment]
Can confirm. `0.0.2` does get things working again on Mac! 🙌 Thanks for your work @joedevivo! I much prefer VS Code to MU Editor, so this extension is amazing!

**Comment by codepope** [comment]
Splendid work Joe! Now working. Sorry I couldn't help more in the debug (tho I know way more about the node-gyp issue now).

**Comment by joedevivo** [comment]
Me too! If you found anything that looks better than my "fix" of checking in all the bindings I built manually on all these platforms, please let me know. I figured they'll only need to be rebuilt when vscode upgrades electron again, or I upgrade these dependencies.

**Comment by dzervas** [comment]
I have this issue in 0.1.2 on Linux. Is there a known workaround?

**Comment by jwlarocque** [comment]
In case anyone runs into this in the future, you need to be in an actual workspace which meets the activation requirements.  If you just have a file open and try to run a command it won't work.
