### ISSUE TITLE
Cannot get it to work on Codium, Linux

### ISSUE THREAD

**Issue by Sciss** [joedevivo/vscode-circuitpython#70]
I installed Codium via recommended [package manager](https://vscodium.com/#install). It's version 1.63.2; system is Debian 11; Python is 3.9.2. I think the marketplace doesn't work with Codium? Finding the extension from within Codium doesn't work. So I download the extension from the website, and install using `codium --install-extension joedevivo.vscode-circuitpython-0.1.15.vsix`.

But I think it's missing a step. I get a notification `Downloading new bundle: 20220105`, but nothing seems to happen. When I try to execute any CircuitPython command, say `CircuitPython: Select Serial Port` , I just get the error `command 'circuitpython.selectBoard' not found`.

Screenshot attached.

Info:

```
Version: 1.63.2
Commit: 899d46d82c4c95423fb7e10e68eba52050e30ba3
Date: 2021-12-17T00:20:01.675Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Linux x64 5.10.0-10-amd64
```

![Screenshot from 2022-01-05 17-27-28](https://user-images.githubusercontent.com/131300/148253860-ffdecbd7-e896-46fa-8222-30d1d9ea08e4.png)

**Comment by Sciss** [comment]
I quit, fixed the marketplace links like this: https://github.com/VSCodium/vscodium/issues/418#issuecomment-643664182

Restarted Codium, now it said 'Bundle already at latest version: 20220105', no more errors so far, 'Select Serial Port' opens selector.

**Comment by mwaterbu** [comment]
> I quit, fixed the marketplace links like this: [VSCodium/vscodium#418 (comment)](https://github.com/VSCodium/vscodium/issues/418#issuecomment-643664182)

This didn't work for me. I have tried installing with the vsix file, and through the market (after doing the fix you suggested), neither way works. How is your Codium installed? I am running the Snap package.

It works fine for me with Codium on Windows when installing through the market.

On Linux, I cannot execute any CircuitPython commands, they all give the not found error. Other extensions from the marketplace work fine.
![image](https://user-images.githubusercontent.com/11249060/175786348-607ac214-3cb5-4b48-96d0-792f2a74d4a7.png)

**Comment by Anonymous941** [comment]
Exact same issue here.  I'd prefer not to switch to VSCode but it looks like I have to
